version: '3'

services:
  db:
    container_name: proyecto_db
    image: mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "4g"
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: proyecto

    ports:
      - "3306:3306"
    networks:
      my_net:
        ipv4_address: "172.28.1.1"

  web:
    container_name: proyecto_web
    depends_on:
      - db
    build:
      context: ./web/.
    deploy:
      resources:
        limits:
          memory: "4g"
    volumes:
      - ./src/:/var/www/html
      - ./web/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./web/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"

    networks:
      my_net:
        ipv4_address: "172.28.1.2"

  phpmyadmin:
    container_name: proyecto_phpmyadmin
    image: phpmyadmin/phpmyadmin
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "4g"
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    # restart: always
    ports:
      - 8080:80
    networks:
      my_net:
        ipv4_address: "172.28.1.3"

networks:
  my_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: "172.28.0.0/16"